skip_output:
  - meta # Skips lefthook version printing
  - empty_summary # Skips summary heading when there are no steps to run
  - execution # Skips printing any execution logs (but prints if the execution failed)
  - execution_out # Skips printing execution output (but still prints failed commands output)
  - skips # Skips "skip" printing (i.e. no files matched)
piped: true # Stop if one of the steps fails
pre-commit:
  parallel: true
  commands:
    npm:
      glob: "package{,-lock}.json"
      run: npm i
      stage_fixed: true
    db:
      glob: "db/*"
      run: node_modules/.bin/astro check
      stage_fixed: true
    locales:
      glob: "src/locales/*"
      run: node_modules/.bin/i18n-typegen codegen
      stage_fixed: true
    biome:
      glob: "*.{js,jsx,mjs,cjs,ts,tsx,mts,cts,json}"
      run: node_modules/.bin/biome check --apply {staged_files}
      stage_fixed: true