// Generated by Wrangler on Wed Mar 27 2024 11:19:56 GMT+0100 (Central European Standard Time)
// by running `wrangler types`

// biome-ignore lint/complexity/noBannedTypes: generated file
type Env = {};
