/* eslint-disable prettier/prettier */
// prettier-ignore

/**
 * Generated by i18n-type-generator
 * https://github.com/BeTomorrow/i18n-typegen
 */

declare module "translations" {
	type Translations = {
		"blog.title": undefined;
		"blog.page-title": undefined;
		"blog.subtitle": undefined;
		"blog.description": undefined;
		"newsletter.subscribe": undefined;
		"newsletter.title": undefined;
		"newsletter.description": undefined;
		"newsletter.cancel": undefined;
		"floating.contact": undefined;
		"404.title": undefined;
		"404.text": undefined;
		"404.button": undefined;
		"families.title": undefined;
		"families.intro.h1": undefined;
		"families.intro.p": undefined;
		"families.book.title": undefined;
		"families.book.subtitle": undefined;
		"families.book.intro": undefined;
		"families.book.text": undefined;
		"families.book.success": undefined;
		"families.book.workshop": undefined;
		"museums.title": undefined;
		"museums.intro.h1": undefined;
		"museums.intro.p": undefined;
		"museums.offer": undefined;
		"museums.tagline": undefined;
		"museums.research.title": undefined;
		"museums.research.p": undefined;
		"museums.insights.title": undefined;
		"museums.insights.p": undefined;
		"museums.tell.title": undefined;
		"museums.tell.p": undefined;
		"team.title": undefined;
		"team.about": undefined;
		"team.speeches": undefined;
		"team.publications": undefined;
		"team.exhibitions": undefined;
		"team.translations": undefined;
		"team.ellen.about": undefined;
		"team.ellen.text": undefined;
		"team.ellen.publications": undefined;
		"team.ellen.translations": undefined;
		"team.ellen.speeches": undefined;
		"team.anka.about": undefined;
		"team.anka.text": undefined;
		"team.anka.speeches": undefined;
		"team.anka.publications": undefined;
		"meta.description": undefined;
		"home.title": undefined;
		"home.h1": undefined;
		"home.more": undefined;
		"home.intro": undefined;
		"home.collaboration.title": undefined;
		"home.collaboration.subtitle": undefined;
		"home.collaboration.description.p1": undefined;
		"home.collaboration.description.p2": undefined;
		"home.offer": undefined;
		"home.for.families.title": undefined;
		"home.for.families.description": undefined;
		"home.for.companies.title": undefined;
		"home.for.companies.description": undefined;
		"home.for.culture.title": undefined;
		"home.for.culture.description": undefined;
		"home.pre-research.title": undefined;
		"home.pre-research.description.p1": undefined;
		"home.pre-research.description.p2": undefined;
		"home.research.title": undefined;
		"home.research.description": undefined;
		"home.evaluation.title": undefined;
		"home.evaluation.description": undefined;
		"home.texting.title": undefined;
		"home.texting.description": undefined;
		"home.contact.submit": undefined;
		"home.contact.title": undefined;
		"home.contact.firstName": undefined;
		"home.contact.lastName": undefined;
		"home.contact.email": undefined;
		"home.contact.message": undefined;
		"home.contact.privacy": undefined;
		"home.contact.coupon": undefined;
		"home.contact.get-to-know": undefined;
		"home.contact.success": undefined;
		"home.conditions.title": undefined;
		"home.conditions.subtitle": undefined;
		"home.conditions.p1": undefined;
		"home.conditions.p2": undefined;
		"home.conditions.consulting.heading": undefined;
		"home.conditions.consulting.li1": undefined;
		"home.conditions.consulting.li2": undefined;
		"home.conditions.consulting.li3": undefined;
		"home.conditions.consulting.li4": undefined;
		"home.conditions.consulting.li5": undefined;
		"home.conditions.facts.heading": undefined;
		"home.conditions.facts.p1": undefined;
		"home.conditions.searches.heading": undefined;
		"home.conditions.searches.p1": undefined;
		"home.conditions.research.heading": undefined;
		"home.conditions.research.li1": undefined;
		"home.conditions.research.li2": undefined;
		"home.conditions.research.li3": undefined;
		"home.conditions.exhibitions.heading": undefined;
		"home.conditions.exhibitions.li1": undefined;
		"home.conditions.exhibitions.li2": undefined;
		"home.conditions.exhibitions.li3": undefined;
		"home.conditions.exhibitions.li4": undefined;
		"home.conditions.exhibitions.li5": undefined;
		"home.conditions.exhibitions.li6": undefined;
		"imprint.title": undefined;
		"privacy.title": undefined;
	};

	type TranslationKeys = keyof Translations;

	type TranslationFunctionArgs<T extends TranslationKeys> =
		T extends TranslationKeys
			? Translations[T] extends undefined
				? [key: T]
				: [key: T, interpolates: Translations[T]]
			: never;

	type TranslationFunction = <T extends TranslationKeys>(
		...args: TranslationFunctionArgs<T>
	) => string;

	export type { TranslationFunction, TranslationFunctionArgs, TranslationKeys };
}
