name: Lighthouse CI
on:
    issue_comment:
      types: [created, edited]
    
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.comment.user.login, 'cloudflare') && !contains(github.event.comment.body, 'in progress')  }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Deployment URL
        id: get_deployment_url
        run: |
          URL=$(echo "${{ github.event.comment.body }}" | grep href | grep -Eo 'https://[a-zA-Z0-9./?=_%:-]*' | sort -u | head -n 1)
          echo "url=$URL" >> $GITHUB_OUTPUT
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        env:
            LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        with:
          configPath: ./lighthouserc.cjs
          urls: |
            ${{ steps.get_deployment_url.outputs.url }}/en/
            ${{ steps.get_deployment_url.outputs.url }}/de/
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
