name: Lighthouse CI
on:
    issue_comment:
      types: [created, edited]
    
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.user.name == 'cloudflare-pages' }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Deployment URL
        id: get_deployment_url
        run: |
          URL=$(echo "${{ github.event.comment.body }}" | grep href | grep -Eo 'https://[a-zA-Z0-9./?=_%:-]*' | sort -u | head -n 1)
          echo "url=$URL" >> $GITHUB_OUTPUT
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            ${{ steps.get_deployment_url.outputs.url }}/en/
            ${{ steps.get_deployment_url.outputs.url }}/de/
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
          