name: Lighthouse CI
on:
    check_run:
      types: [completed]
    
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Deployment URL
        id: get_deployment_url
        run: |
          echo "${{ github.event.check_run.output.text }}" "${{ github.event.check_run.output.summary }}"
          echo "url=$(echo "${{ github.event.check_run.output.summary }}" | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | sort -u | head -n 1" >> $GITHUB_OUTPUT
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            ${{ steps.get_deployment_url.outputs.url }}/
            ${{ steps.get_deployment_url.outputs.url }}/en/
            ${{ steps.get_deployment_url.outputs.url }}/de/
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage