name: Lighthouse CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: lighthouse-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
    
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      deployments: write
      actions: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Await CF Pages
        uses: WalshyDev/cf-pages-await@3abae9f62a7672a1701300702ce42908e16cb88a # v1
        id: cf
        with:  
          apiToken: ${{ secrets.CF_API_TOKEN }}  
          accountId: 'cd1e88db5a44de0f45317275cbcef879'
          project: 'rahlwes-eu'
          githubToken: ${{ github.token }}
          commitHash: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@1b0e7c33270fbba31a18a0fbb1de7cc5256b6d39 # v11
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_GITHUB_TOKEN: ${{ github.token}}
        with:
          configPath: ./.lighthouserc.cjs
          urls: |
            ${{ steps.cf.outputs.url }}/en/
            ${{ steps.cf.outputs.url }}/de/
            ${{ steps.cf.outputs.url }}/en/does-not-exist/
            ${{ steps.cf.outputs.url }}/de/does-not-exist/
            ${{ steps.cf.outputs.url }}/en/team/
            ${{ steps.cf.outputs.url }}/de/team/
            ${{ steps.cf.outputs.url }}/en/museums/
            ${{ steps.cf.outputs.url }}/de/museums/
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
